sample_tuple = ('oranges', 'apples', 'watermelons', 'guavas', 'pomogranates')
modify_tuple = list(sample_tuple)
print(modify_tuple)
modify_tuple.append("chickoo")
modify_tuple.append("jackfruit")
modify_tuple.append("mangoes")
modify_tuple.append("grapes")
print(modify_tuple)
tupled = tuple(modify_tuple)
print(tupled)
